# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50, null=True)),
                ('productlongname', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctypeid', models.CharField(max_length=15)),
                ('productdesc', models.CharField(max_length=40, null=True)),
                ('productsize', models.CharField(max_length=40, null=True)),
                ('issale', models.IntegerField()),
                ('saletime', models.DateTimeField(default=None, null=True)),
                ('productnum', models.IntegerField(default=0)),
                ('storenums', models.IntegerField()),
                ('review', models.IntegerField()),
                ('coin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=10)),
                ('typename', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='ftypeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Type'),
        ),
    ]
