# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0003_auto_20190315_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'px_goodsimg',
            },
        ),
        migrations.AlterModelTable(
            name='carousel',
            table='px_carousel',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='px_goods',
        ),
        migrations.AlterModelTable(
            name='type',
            table='px_type',
        ),
        migrations.AlterModelTable(
            name='user',
            table='px_user',
        ),
        migrations.AddField(
            model_name='goodsimg',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Goods'),
        ),
    ]
