# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0004_auto_20190315_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='img',
            field=models.CharField(default='', max_length=100),
        ),
    ]
