# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0005_goods_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.User')),
            ],
            options={
                'db_table': 'pc_cart',
            },
        ),
    ]
