# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0006_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='px_cart',
        ),
    ]
