# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0008_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
